#pragma once

#include  "NativeGameplayTags.h"

namespace DGGameplayTags
{
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Player)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Object)
	
	// Skill
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Common_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Common_Sprint)

	// State
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sprint)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Jump)

	// Block
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Movement_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Movement_Sprint)
}