#pragma once

#include  "NativeGameplayTags.h"

namespace DGGameplayTags
{
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Player)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Object)
	
	// Input
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_1)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_2)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_3)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_4)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_Q)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_E)
	
	// Skill_Common
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Common_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Common_Sprint)
	
	// Skill_Warrior
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Warrior_SharpStrike)

	// State
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sprint)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Jump)
	
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Skill_Warrior_SharpStrike_Active)

	// Block
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Movement_Dodge)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Movement_Sprint)
}