#pragma once

#include  "NativeGameplayTags.h"

namespace DGGameplayTags
{
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Player)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy)
	PROJECTDG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Object)
}